### PR TITLE
C++ fixups, improve performance, clean up code a little, etc

### PR DESCRIPTION
**Pull request by cculianu**
This should hopefully help things be faster and more correct.

Addresses issues #1  and #2, as well as contains other fixups.

---

Note that this is not fully tested.  I am on macOS and the plugin doesn't work there for some reason.  Please test this (rebuild the binary, package the plugin, try it out) and let me know if it performs better, etc.

### CODE REVIEW

**Comment by cculianu** [comment]
I just pushed a bunch of additional commits...

**Comment by TinosNitso** [comment]
Hi, I've successfully built the code exactly as you've provided, in Win10, and I've tested it by replacing the new & old .exe. Speed-wise there's no improvement in my simple tests, although your code is technically more elegant. The two builds are exactly the same number of bytes, making them hard to distinguish. For speed testing, I got the following:
Pattern New MH/s Old MH/s
0           0.01            0.0
00         0.03            0.03
000       0.08            0.1
0000     0.5              0.58
00000   1.3              1.3
000000 1.91            1.9
(You win some, you lose some...)
This is after clicking on the 'Mine' button with the following TX input:
01000000018131f8c152097ce3d44d448bab7dc37c8b2e1186a19678e662cb65094600000000000000720008020000000005128c4125c8cab9a393d2933f892e7e63ede55c03996fef307ca51a345f9251bd95152beb991e9bfa49047adfa0a4c3306d881e9051b597ba8e56b80c954f74c7b37dce412521039eb296a68925e890502b54881b220bb108d1c0676236a3180d5eb398e81c4f90ac7777feffffff013d0f00000000000017a914f3aa0152467116c48638e01ff028256281f969898743de0a00
The main improvement is std::once_flag.
I'd like to move code out of Hasher and into main, so that we don't keep calculating all the constants inside each thread. Since I'll be doing some new builds I may as well.
I'm interested in including "util/streencodings.cpp" so that we don't need to spell out the hexTable.
On the Python side I want an Example button so people can test the binaries immediately. UI probably needs tooltips more than placeholder text. There should be feedback whenever 'Sign...' button fails to do anything. I'm also interested in an animated tab icon (with disable checkbox). e.g. another plugin may want a slowly waving BCH flag ((16px)**2 res), and this plugin is like an example/template.
Even with much better C++ code, there may or may not be enough for another release.

**Comment by cculianu** [comment]
Does my code work? I may have missed something.  Yeah glad you took it for a spin.  I intended it more as illustrative than anything.  Feel free to take whatever pieces inspire you -- or include strencodings.cpp (although I think that may pull in more deps too, in a neverending cycle of deps).  

Yeah speed-wise it's no win. I initially misread the code and thought it was doing more back-and-forth to/from hex<->binary but it's not.  So yeah it's just for elegance's sake.  As a C++ veteran.. that 1-arg FromHex() function was scary to read!! Ha ha.

If you see no real benefit in this code, no sweat.  This is just here for illustration like I said.

Great work on the plugin man this is great.  Also an address vanitygen thing might be nice too -- although that's a bit harder to do right on account of the ripemd stuff and more steps in between.

Looking forward to more iterations of this as it evolves!

---

> The main improvement is std::once_flag.

Yeah I think that's the only real critical piece here that is different / useful.  Everything else in my PR is "aesthetics".  I do recommend you use that `std::once_flag` thing tho, if nothing else.  You can just snipe that out.

**Comment by TinosNitso** [comment]
I have no idea how to handle pull requests or issues. I've uploaded a .cpp which I'd like to use in the next release builds.
[https://github.com/TinosNitso/VanityTXID-Plugin/blob/main/src/main-RESPONSE_TO_cculianu.cpp](https://github.com/TinosNitso/VanityTXID-Plugin/blob/main/src/main-RESPONSE_TO_cculianu.cpp)
Is it OK?
The 1.4.0 main.cpp was 3kB, your version is 6kB, and my response is 4kB. My build is slightly bigger than yours, and your build size was exactly the same as 1.4.0 (a miracle?). My build is a tiny bit bigger due to moving all **FromHex** calculations into the main function.

Edit: Thanks to **std::once_flag** the Python script needs only Process.communicate()[0].decode()

**Comment by cculianu** [comment]
> build size was exactly the same as 1.4.0 (a miracle?). 

Not surprising. These days the C++ optimizer totally transforms code. If you care about build size, try building with `-Os` option (optimize for size). That may even be smaller.

>

Looks good! And you tested it and it's correct?  Only comment is: *theoretically* the following may fail under *extremely rare* circumstances:

```c++
threads[0].join();// block forever, waiting for at least 1 thread to succeed
```

I would definitely change it to:

```c++
for (auto & thr : threads) thr.join(); // block forever, waiting for at least 1 thread to exit the program
```

How can it fail?  Consider the `return` statement in `Hasher` -- and how it can be reached in extremely unlikely circumstances if 1 thread X "finishes" and calls `Exit`, first but somehow is not scheduled until its buddy thread 0 also "finishes", and so the `call_once` is skipped in thread 0, and it does `return`, before thread X can actually print to stdout and exit!  This is extremely rare, but theoretically possible thus making the code you have not guaranteed to always succeed, whereas if you try and join all threads it is guaranteed to halt only after printing results to stdout.

**Comment by TinosNitso** [comment]
I prefer -O3 instead of -Os, Code::Blocks doesn't let me set both.
In the next release I'll round hash rate to 3 decimal places instead of 2, because all this FromHex stuff only really affects singleton patterns (e.g. pattern '0'). For those we get 0.0 MH/s half the time, but it's interesting to look at the 3rd decimal.
I've updated a new main.cpp [here](https://github.com/TinosNitso/VanityTXID-Plugin/blob/main/src/main-RESPONSE_TO_cculianu.cpp). (EDIT: I've included everything I like in the standard main.cpp for v1.4.1.)
I think removing the 'return' line solves the .joins problem.
I'd honestly rather keep the C++ as simple as humanly possible, whilst not in any way sacrificing the in-thread hash rate. Failing to use static, or const, etc, is perfectly acceptable to me, depending exactly when. I'm wondering how simple C++ can be, like Python. If anyone can ever prove an "optimization" makes the hash rate Number-Go-Up, then I'll reconsider.
I've added std::getchar() for when someone accidentally double-clicks the exe.

**Edit**: I take back the thing about 3 decimals, I still get 0.0 MH/s some of the time. Better to stick with only 2.

**Comment by cculianu** [comment]
> Failing to use static, 

Except static tells the optimizer it can in-line your function or otherwise simplify it.  It helps the optimizer out -- especially when the function is actually not called by anything outside of your file. It also makes the binary smaller.

**Comment by TinosNitso** [comment]
> makes the binary smaller
I've figured out using **uint8_t** hexList[103] brings my new build down to the exact size of your build = old build size. int hexList was too big. The .exe build size, 88,576 bytes, is usually a multiple of 512 bytes (173x for us).

**Comment by cculianu** [comment]
You know build size hardly matters that much, esp if it's on the order of kb differences right? Why do you want to optimize for that?

**Comment by TinosNitso** [comment]
I have some bad news. v1.4.0 is about **0.5%** faster than both of our best attempts. The problem appears to be that arrays are faster than vectors. 0.5% is so little I didn't notice it until now. I've tested again and again, and v1.4.0 is the best.

IMO build size is like the 2nd most important thing, after hash rate. It's actually real and could affect the UX, since users might check the **exact** build size to see whether there's any obvious malware.

Edit: The more tests I do, the more sure I am. I can speed up my best code by switching the TXn from vector to array. Using vectors is probably a bad habit, and best practice might just be to get rid of them entirely, just in case anyone ever has to go through this ever again. o m g

**Comment by cculianu** [comment]
> The problem appears to be that arrays are faster than vectors. 0.5% is so little I didn't notice it until now. I've tested again and again, and v1.4.0 is the best.

They probably aren't faster.  Under the hood they are similar. Both are really just arrays. You lack experience with C++ and draw crazy conclusions man.  0.5% is within modern CPU error bars.

You can do what you like, this is your project.  I was trying to guide you towards more modern and maintainable techniques, but you seem to insist on doing things your way.  

I think each developer must sometimes walk their own walk ...  I tried to help. It's proving frustrating for me to do so.  Good luck.

**Comment by TinosNitso** [comment]
I have enough experience to know that you are wrong. Anyone even suggesting the use of **vectors** is just trolling either me or you.

Edit: I believe v1.4.1 is at least (or maybe only) 0.1% faster than this pull request. However the new release uses 'goto GoTo' in the deepest loop, so that might be why. Eventually I might even code a UI option to switch the binary over to a fully vector version, to prove that vectors aren't as fast as **arrays**.

**Pull request closed without merging**
